name: ptncenter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
    sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_lints: ^5.0.0
  firebase_analytics: ^11.4.1
  carousel_slider: ^5.0.0
  barcode_scan2: ^4.4.0
  shared_preferences: ^2.5.1
  toast: ^0.3.0
  permission_handler: ^11.3.1
  youtube_player_flutter: ^9.1.1
  youtube_player_iframe: ^5.2.2

  chat_bubbles: ^1.7.0
  font_awesome_flutter: ^10.8.0
  google_maps_flutter: ^2.10.0
  awesome_dialog: ^3.2.1
  stylish_bottom_bar: ^1.1.1
  loader_overlay: ^5.0.0
  loading_animation_widget: ^1.3.0
  mobile_scanner: ^7.0.1
  image: ^4.5.4
  image_picker: ^1.1.2
  webview_flutter: ^4.13.0
  platform: ^3.1.6

  flutter_overlay_loader: ^2.0.0  #request to change
  popup_banner: ^1.0.0  #request to change
  rflutter_alert: ^2.0.7   #request to change
  flutter_spinbox: ^0.13.1  #request to change
  favorite_button: ^0.0.4 #request to change
  status_alert: ^1.0.1 #request to change
  loading_indicator: ^3.1.1    #request to change   19m
  # flutter_webview_plugin: ^0.4.0  #request to change
  # flutter_barcode_scanner: ^2.0.0  #request to change


dev_dependencies:
  flutter_test:
    sdk: flutter
    
  # scan_preview:


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/logo.png
    - images/shopping_cart.png
    - images/icon_googlemap.jpg
    - images/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Sarabun
      fonts:
        - asset: fonts/Sarabun-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
